config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :personal_trainings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'persons/profile'
  root 'persons#main'

  get 'persons/main', as: 'user_root'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :personal_training

  scope :ordered, proc{ order(:id) }
end

app/models/personal_training.rb
class PersonalTraining < ActiveRecord::Base
  belongs_to :user
  has_many :exercises

  accepts_nested_attributes_for :exercises, :allow_destroy => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, :stage, :age, :weight, :height, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :personal_trainings
  has_one :profile

  def self.not_trainer
    all.select{ |u| u.profile.try(:is_trainer) == false || u.profile.try(:is_trainer) == nil }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  DAYNAMES_RU = {"Sunday" => 'Воскресенье', "Monday" => 'Понедельник', "Tuesday" => 'Вторник', "Wednesday" => 'Среда', "Thursday" => 'Четверг', "Friday" => 'Пятница', "Saturday" => 'Суббота'}

end

app/controllers/personal_trainings_controller.rb
class PersonalTrainingsController < ApplicationController
  before_action :set_personal_training, only: [:show, :edit, :update, :destroy]

  # GET /personal_trainings
  # GET /personal_trainings.json
  def index
    @personal_trainings = PersonalTraining.all
  end

  # GET /personal_trainings/1
  # GET /personal_trainings/1.json
  def show
  end

  # GET /personal_trainings/new
  def new
    @personal_training = PersonalTraining.new
  end

  # GET /personal_trainings/1/edit
  def edit
  end

  # POST /personal_trainings
  # POST /personal_trainings.json
  def create
    @personal_training = PersonalTraining.new(personal_training_params)

    respond_to do |format|
      if @personal_training.save
        format.html { redirect_to @personal_training, notice: 'Personal training was successfully created.' }
        format.json { render :show, status: :created, location: @personal_training }
      else
        format.html { render :new }
        format.json { render json: @personal_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_trainings/1
  # PATCH/PUT /personal_trainings/1.json
  def update
    respond_to do |format|
      if @personal_training.update(personal_training_params)
        format.html { redirect_to @personal_training, notice: 'Personal training was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_training }
      else
        format.html { render :edit }
        format.json { render json: @personal_training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_trainings/1
  # DELETE /personal_trainings/1.json
  def destroy
    @personal_training.destroy
    respond_to do |format|
      format.html { redirect_to personal_trainings_url, notice: 'Personal training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_training
      @personal_training = PersonalTraining.find(params[:id])
    end

    def personal_training_params
      params.require(:personal_training).permit(:name, :description, :weekday, :user_id, exercises_attributes: [:id, :name, :description, :attempt, :quantity])
    end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  
  def main
    if current_user.profile
      
    else
      redirect_to new_profile_path
    end
  end

  def profile
  	puts current_user.profile.inspect
  	if current_user.profile.try(:id)
  	  if current_user.profile.is_trainer
        redirect_to personal_trainings_path
  	  else
  	    @trainings = current_user.personal_trainings.where(weekday: Time.now.strftime("%A"))
  	  end
  	else
  	  redirect_to new_profile_path
   	end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < InheritedResources::Base
 
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to root_path
    else
      redirect_to new_profile_path
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:allow_create_training, :name, :age, :user_id, :is_trainer, :weight, :height, :stage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_trainings_helper.rb
module PersonalTrainingsHelper
  def user_info(u)
    "#{u.profile.try(:name)}, возраст - #{u.profile.try(:age)}, вес - #{u.profile.try(:weight)}, рост - #{u.profile.try(:height)}".to_s
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Спортивный клуб</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    body {
      background: url(<%= asset_path('wp1.jpg') %>);
      background-size: cover;
      color: #ffffff;
      font-size: 120%;
      text-shadow: 1px 1px 2px black, 0 0 1em gray;
    }
    #maincontent {
      padding: 25px;
      -webkit-box-shadow: 2px 2px 8px 0px rgba(50, 50, 50, 0.75);
      -moz-box-shadow:    2px 2px 8px 0px rgba(50, 50, 50, 0.75);
      box-shadow:         2px 2px 8px 0px rgba(50, 50, 50, 0.75);
    }
    table {
      color: #000000;
      text-shadow: none;
    }
    .navbar-default .navbar-nav > li:not(:last-child) {
      border-right:1px solid #ddd;
     }

    .navbar-default .navbar-nav > li:not(:first-child) {
      border-left:1px solid #fff;
     }

    .navbar-inverse .navbar-nav > li:not(:last-child) {
      border-right:1px solid #000;      
     }

    .navbar-inverse .navbar-nav > li:not(:first-child) {
      border-left:1px solid #444;
     }
    .navbar-inverse a {
      text-decoration: none !important;
    }
    input, select {
      color: #000000;
    }
  </style>
</head>
<body>

<%= render 'shared/nav' %>

<div class="container">
  <div class="row">
    <div class="container message">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div id="maincontent">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/personal_trainings/_exercise_fields.html.slim
.nested-fields
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :description
    br
    = f.text_field :description
  .field
    = f.label :attempt
    br
    = f.number_field :attempt
  .field
    = f.label :quantity
    br
    = f.number_field :quantity
  = link_to_remove_association "Удалить упражнение", f

app/views/personal_trainings/_form.html.slim
= form_for(@personal_training) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :user_id
    = f.select :user_id, User.not_trainer.map{ |u| [ user_info(u), u.id ] }, {}, class: "form-control", style: 'width: 550px; display:inline;'
  .field
    = f.label 'День недели'
    - daynames = {"Monday" => 'Понедельник', "Tuesday" => 'Вторник', "Wednesday" => 'Среда', "Thursday" => 'Четверг', "Friday" => 'Пятница', "Saturday" => 'Суббота', "Sunday" => 'Воскресенье'}
    = f.select :weekday, daynames.map{ |k,v| [v, k]}, {}, class: "form-control", style: 'width: 550px; display:inline;'
  .field
    #exercises
      = f.fields_for :exercises do |exercise|
        = render 'exercise_fields', f: exercises 
      .links
        = link_to_add_association 'Добавить упражнение', f, :exercises
  .actions
    = f.submit 'Применить'

app/views/personal_trainings/edit.html.erb
<h1>Изменить</h1>

<%= render 'form' %>

<%= link_to 'Показать', @personal_training %> |
<%= link_to 'Назад', personal_trainings_path %>

app/views/personal_trainings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Тренировки</h1>

<table class='table'>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_trainings.each do |personal_training| %>
      <tr class='active'>
        <td><%= personal_training.user.profile.try(:name) %></td>
        <td><%= link_to 'Показать', personal_training %></td>
        <td><%= link_to 'Редактировать', edit_personal_training_path(personal_training) %></td>
        <td><%= link_to 'Удалить', personal_training, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая тренировка', new_personal_training_path %>

app/views/personal_trainings/new.html.erb
<h1>Новая тренировка</h1>

<%= render 'form' %>

<%= link_to 'Назад', personal_trainings_path %>

app/views/personal_trainings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редактировать', edit_personal_training_path(@personal_training) %> |
<%= link_to 'Назад', personal_trainings_path %>

app/views/persons/main.html.slim
img src='bb.png' width='200px;'
h2 Спортивный клуб
h3 Быстрее, выше, сильнее.
p Данное приложение служит для того, чтобы все пользователи имели доступ к тренировкам, которые составляют для него тренера.

app/views/persons/profile.html.slim
- if @trainings.count > 0
  -if current_user.profile.try(:name)
    h3= current_user.profile.name
  h2 Список тренировок
  - @trainings.each do |training|
    h3= training.name
    p= training.description
    table.table
      thead
        tr
          th Упражнение
          th Описание
          th Выполнений
          th Подходов
      tbody
        - training.exercises.ordered.each do |exercise|
          tr.active
            td= exercise.name
            td= exercise.description
            td= exercise.quantity
            td= exercise.attempt
- else
  h2 У Вас на сегодня нет ни одной тренировки

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :is_trainer %><br>
    <%= f.check_box :is_trainer %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.number_field :stage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Allow create training</th>
      <th>Name</th>
      <th>Age</th>
      <th>User</th>
      <th>Is trainer</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Stage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.allow_create_training %></td>
        <td><%= profile.name %></td>
        <td><%= profile.age %></td>
        <td><%= profile.user_id %></td>
        <td><%= profile.is_trainer %></td>
        <td><%= profile.weight %></td>
        <td><%= profile.height %></td>
        <td><%= profile.stage %></td>
        <td><%= link_to 'Показать', profile %></td>
        <td><%= link_to 'Редактировать', edit_profile_path(profile) %></td>
        <td><%= link_to 'Удалить', profile, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый профиль', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Новый профиль</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Allow create training:</strong>
  <%= @profile.allow_create_training %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<p>
  <strong>Is trainer:</strong>
  <%= @profile.is_trainer %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @profile.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @profile.height %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @profile.stage %>
</p>

<%= link_to 'Редактировать', edit_profile_path(@profile) %> |
<%= link_to 'Назад', profiles_path %>

app/views/shared/_nav.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'На главную', root_path
        - if current_user.try(:profile)
          li
            = link_to 'Профиль', profile_path(current_user.profile)
          - if current_user.profile.try(:is_trainer)
            li
              = link_to 'Управление тренировками', personal_trainings_path
          - else
            li
              = link_to 'Мои тренировки', persons_profile_path
        - if current_user
          li
            = link_to 'Выйти', destroy_user_session_path, :method => :delete
        - else
          li
            = link_to 'Войти', new_user_session_path
          li
            = link_to 'Зарегистрироваться', new_user_registration_path
        